### ISSUE TITLE
Pull request creation failed. Validation failed: must be a collaborator

### ISSUE THREAD

**Issue by Zain-ul-din** [aborazmeh/awesome-palestine#33]
Hey @aborazmeh I'm getting this error when creating PR please can you fix it?

```diff
- Pull request creation failed. Validation failed: must be a collaborator
```

**Comment by aborazmeh** [comment]
I don't think it's related to our repository, as I didn't change any settings recently. It seems to be a common GitHub fault.
Refer to this for some suggested solutions:

https://github.com/orgs/community/discussions/61472

**Comment by Zain-ul-din** [comment]
Perhaps, it will be a fault on my side.
